% the Main Simulation File (MSF) to run simulation CSMA/CD
clear all; clc; close all; 
global global_info

global_info.semafore = 0; %is the medium busy ?
global_info.STOP_AT = 500;
global_info.Collision = [0 0 0 0 0 0 0 0];
pns = pnstruct({'PDF_Common','PDF_ClientCD','PDF_ClientCD2','PDF_ClientCD3','PDF_ClientCD4','PDF_ClientCD5','PDF_ClientCD6','PDF_ClientCD7','PDF_ClientCD8','PDF_MediumCD'}); % create petri net structure

dyn.ft = {'tGen','unifrnd(5,20)','tWaitColl','unifrnd(10,20)',...
            'tGen2','unifrnd(5,20)','tWaitColl2','unifrnd(10,20)',...
            'tGen3','unifrnd(5,20)','tWaitColl3','unifrnd(10,20)',...
            'tGen4','unifrnd(5,20)','tWaitColl4','unifrnd(10,20)',...
            'tGen5','unifrnd(5,20)','tWaitColl5','unifrnd(10,20)',...
            'tGen6','unifrnd(5,20)','tWaitColl6','unifrnd(10,20)',...
            'tGen7','unifrnd(5,20)','tWaitColl7','unifrnd(10,20)',...
            'tGen8','unifrnd(5,20)','tWaitColl8','unifrnd(10,20)',...
            'tAck',10,'allothers', 1};
dyn.ip={'tIn',2, 'tCollision',1};
pni = initialdynamics(pns, dyn);

Sim_Results = gpensim(pni); % perform simulation runs
%prnss(Sim_Results); % print the simulation results 
figure;plotp(Sim_Results, {'pCollision','pAck','pTotalSent'}); % plot the results
figure;plotp(Sim_Results,{'pNbSent','pNbSent2','pNbSent3','pNbSent4','pNbSent5','pNbSent6','pNbSent7','pNbSent8'})