% the Main Simulation File (MSF) to run simulation CSMA/CA
clear all; clc; close all; 
global global_info

global_info.semafore = 0; %is the medium busy ?
global_info.STOP_AT = 500;
pns = pnstruct({'PDF_Common','PDF_MediumCA','PDF_ClientCA','PDF_ClientCA2','PDF_ClientCA3','PDF_ClientCA4','PDF_ClientCA5','PDF_ClientCA6','PDF_ClientCA7','PDF_ClientCA8'}); % create petri net structure

dyn.ft = {'tGen','unifrnd(5,20)','tWaitIdle','unifrnd(10,50)','tWaitSend',5,...
            'tGen2','unifrnd(5,20)','tWaitIdle2','unifrnd(10,50)','tWaitSend2',5,...
            'tGen3','unifrnd(5,20)','tWaitIdle3','unifrnd(10,50)','tWaitSend3',5,...
            'tGen4','unifrnd(5,20)','tWaitIdle4','unifrnd(10,50)','tWaitSend4',5,...
            'tGen5','unifrnd(5,20)','tWaitIdle5','unifrnd(10,50)','tWaitSend5',5,...
            'tGen6','unifrnd(5,20)','tWaitIdle6','unifrnd(10,50)','tWaitSend6',5,...
            'tGen7','unifrnd(5,20)','tWaitIdle7','unifrnd(10,50)','tWaitSend7',5,...
            'tGen8','unifrnd(5,20)','tWaitIdle8','unifrnd(10,50)','tWaitSend8',5,...
            'tAck',10,'tCollision',5,'allothers', 1};

dyn.ip={'tIn',2, 'tCollision',1};
pni = initialdynamics(pns, dyn);

Sim_Results = gpensim(pni); % perform simulation runs
%prnss(Sim_Results); % print the simulation results 
figure;plotp(Sim_Results, {'pCollision','pAck','pTotalSent'}); % plot the results
figure;plotp(Sim_Results, {'pNbSent','pNbSent2','pNbSent3','pNbSent4','pNbSent5','pNbSent6','pNbSent7','pNbSent8'}); % plot the results