%Comom module
function [png] = PDF_Common()

png.PN_name = 'link'; % module name or label
png.set_of_Ps = {'pTransi','pTotalSent'}; % set of places
png.set_of_Ts = {}; % set of transitions 
png.set_of_As = {'tSend','pTransi',1,'tSend','pTotalSent',1,...
        'tSend2','pTransi',1,'tSend2','pTotalSent',1,...
        'tSend3','pTransi',1,'tSend3','pTotalSent',1,...
        'tSend4','pTransi',1,'tSend4','pTotalSent',1,...
        'tSend5','pTransi',1,'tSend5','pTotalSent',1,...
        'tSend6','pTransi',1,'tSend6','pTotalSent',1,...
        'tSend7','pTransi',1,'tSend7','pTotalSent',1,...
        'tSend8','pTransi',1,'tSend8','pTotalSent',1,...
        'pTransi','tIn',1
    }; % set of arcs}; % set of arcs


